### ISSUE TITLE
Support Lodash methods as function parameters and identifiers

### ISSUE THREAD

**Issue by mduvall** [megawac/babel-plugin-lodash#10]
These will currently not generate import methods:

```js
import {map, foo} from 'lodash';

map([1, 2, 3], foo); // foo is undefined
```

or this:

```js
import {foo} from 'lodash';

function something() {
  return foo;
}
```

**Comment by megawac** [comment]
I'm not sure I'd want to support the second case as it'd end up leading down a slippery slope of things to support. Other things I think I'd rather leave out of scope for this are things like 

```
import {map} from 'lodash'
var x = map

var y = {
  x: map
}
``` 

etc.

Thanks for adding the first case though, that's definitely useful
