### ISSUE TITLE
Suggestion: add docs for babel 5.x users

### ISSUE THREAD

**Issue by austinmao** [megawac/babel-plugin-lodash#12]
It took me a bit to figure out that I had to use v0.2.0 for my babel 5 instance. It would be helpful to add some docs for the old schoolers like me :)

**Comment by megawac** [comment]
Yeah, good point a couple people have had issues with non compatible Babel versions.

**Comment by developit** [comment]
If you mean just for Babel itself, they are hosted here:
https://developit.github.io/babel-legacy-docs/

**Comment by megawac** [comment]
nah, I meant for this plugin

**Comment by developit** [comment]
Ah, apologies
