### ISSUE TITLE
es to es

### ISSUE THREAD

**Issue by jdalton** [megawac/babel-plugin-lodash#14]
Would this plugin be able to integrate into the [rollup](https://github.com/rollup/rollup/issues/45#issuecomment-168215190) or [webpack 2](https://github.com/webpack/webpack/issues/1750) dev setup to enable tree-shaking?

**Comment by megawac** [comment]
How do you mean @jdalton? Both rollup and webpack have Babel plugins which would allow people to use this plugin. (I have not used either to confirm they work.)

https://github.com/rollup/rollup-plugin-babel
https://github.com/babel/babel-loader

**Comment by jdalton** [comment]
> I have not used either to confirm they work.

That's what I'm asking. I'm not super familiar with babel plugins. It's on my shortlist of things to dig into esp if this gets pulled into the lodash org. I've only seen the output of this plugin generate node `require` calls but I believe that could be turned into ES6 `import` syntax as well?

**Comment by megawac** [comment]
Yeah, it will generate es6 imports if the Babel plugin for modules to commonjs isnt included. The only true requirement imposed is that lodash is imported using es6 syntax 

https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs

**Comment by megawac** [comment]
Anyway, the one thing to note when using Babel with this plugin and either rollup or webpack is that Babel must be run prior to these bundlers. In the case of rollup (and probably webpack?) es2015-modules-commonjs must be disabled

**Comment by jdalton** [comment]
>  In the case of rollup (and probably webpack?) es2015-modules-commonjs must be disabled

Cool! Would you be able to work up a documentation example for that? If not I can dig into it.

**Comment by jdalton** [comment]
Dup of #15.
