### ISSUE TITLE
Resolve lodash path better.

### ISSUE THREAD

**Issue by jdalton** [megawac/babel-plugin-lodash#16]
See https://github.com/gajus/babel-plugin-lodash-modularize/commit/52636687519bf7adc3f115bc9e5eb84c19c687cc#commitcomment-15230797.

Currently the path to lodash is hardcoded as `'./node_modules/lodash'`. Instead it could use `require.resolve` to get the path of lodash. Further tweaking could be done to handle the case Gajus has as well.

**Comment by megawac** [comment]
I don't think `require.resolve` would suffice if dependencies have not been deduped. Another potential issue is if the plugin is installed globally it will be completely incorrect

**Comment by jdalton** [comment]
I'm sure their's a way to do it even if it means creating a temp file which calls `require.resolve` from the cwd and pipes the output back. I'll poke around more this evening.

**Comment by jdalton** [comment]
Ok so you can do:
```js
var module = require('module');

console.log(module._resolveFilename('lodash', {
  'paths': module._nodeModulePaths(process.cwd())
}));
```

**Comment by jdalton** [comment]
`require.resolve` it will throw if it's not found

**Comment by megawac** [comment]
Good stuff, do you have a moment to PR that otherwise I'll look into it tmw

**Comment by jdalton** [comment]
I want to dig in a bit to ensure this API works across Node versions, or see what versions it works on, and report back.

**Comment by jdalton** [comment]
Works on at least 0.6 - 5.0 which is awesome!

**Comment by jdalton** [comment]
Btw support for that API was added https://github.com/nodejs/node/commit/5a49f96505e48d2a1aa3a21233976f41fe1257ce#diff-d1234a869b3d648ebfcdce5a76747d71R181.

**Comment by jdalton** [comment]
I knew there was a way :)

**Comment by jdalton** [comment]
I'll work on a PR tonight.
