### ISSUE TITLE
support question: enabling this only in node modules

### ISSUE THREAD

**Issue by jonathanong** [megawac/babel-plugin-lodash#17]
wondering if anyone has tried enabling only this in all the modules, including node_modules. would be a neat way to automatically slim down builds. some issues are i see are:

- `node_modules` are not ES6, which is not supported by this module
- needs a separate babel loader in webpack probably

just something i thought about, which is probably an over optimization

**Comment by jdalton** [comment]
Hi @jonathanong!

I haven't tried this and I'd be a little concerned with the potential for breaking things but I dig experiments! If you'd like to experiment and report back that would rock.

**Comment by megawac** [comment]
I'm not sure if this is possible but [for the `babel` require hook you can pass ignore with a regex|bool to allow it to include node modules ](https://babeljs.io/docs/usage/require/#usage)

```js
require("babel-register")({
  ignore: false
});
```

It may be possible to do this in a more general fashion (e.g. through the cli/js API/browserify)?

/cc @thejameskyle
