### ISSUE TITLE
the incredible expanding bundle

### ISSUE THREAD

**Issue by boneskull** [megawac/babel-plugin-lodash#19]
So this is curious--I am running my code thru Babel (and finally Browserify).

Whenever I'm using Lodash in my code, I use it like:

```js
import _ from 'lodash';
```

Here's `.babelrc`:

```json
{
  "presets": [
    "es2015"
  ]
}
```

and Browserify command:

```shell
$ browserify --require es6-symbol/implement --require es6-map/implement --require es6-set/implement --standalone mocha --plugin [ bannerify --file .banner.ejs --pkg package.json ] src --outfile dist/mocha.js
```

**Resulting size (bytes) of `dist/mocha.js`: `752278`**

Let's add `babel-plugin-lodash` to the mix:

```json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "lodash"
  ]
}
```

after re-running the same Browserify command above, 

**Resulting size (bytes) of `dist/mocha.js`: `810148`**

what is this I don't even

**Comment by d10** [comment]
Could you post the update as a gist to give us more information?

**Comment by boneskull** [comment]
@d10 k.  I'm experimenting with `lodash-modularize` and getting drastically different results as well; I'll post those too.

**Comment by megawac** [comment]
Mind uploading a bundle with and without the plugin enabled?

**Comment by boneskull** [comment]
OK, here are four builds:

- [no plugins, no nothing](https://gist.github.com/boneskull/569053814cc4c5f97c25)
- [using babel-plugin-lodash](https://gist.github.com/boneskull/b453ae8d2bb785631761)
- [using lodash-modularize](https://gist.github.com/boneskull/2c477b19f412576fe6ed)
- [using lodash-modularize w/ `--compile` flag](https://gist.github.com/boneskull/3d3eb01e26ccf8b9b84f)

That's `752278`, `810148`, `393377` and `425748` bytes, respectively.

**Comment by boneskull** [comment]
with the last two, I generated a replacement build in `./browser/lodash.js` and put it in my `browser` prop of `package.json`:

```json
{
  "lodash": "./browser/lodash"
}
```

**Comment by boneskull** [comment]
fwiw, I'm not using a lot:

```shell
$ lodash-modularize src/**/*.js test/**/*.js --list
assign,defaults,every,forEach,includes,isEmpty,isFunction,isObject,reject,size
```

**Comment by megawac** [comment]
@boneskull it looks like the issue here may be that an npm dependencies is importing lodash and causing the entire lodash bundle to be included once + the custom files imported by this plugin (related #17)

**Comment by boneskull** [comment]
hmm, ok.  I'll regenerate using lodash-modularize against my deps too.

**Comment by boneskull** [comment]
(re the last msg, actually, no, that doesn't seem to make a difference anyway)

**Comment by megawac** [comment]
Anyway, the difference between the first two files (with and without this plugin) is the version with the plugin includes all of lodash in addition to the implementations of the methods you use and the other one only includes all of lodash

**Comment by boneskull** [comment]
thanks.  with that tip I found the problem (which was a place in my code I was still using `require('lodash')`.  sorry for the goose chase!

**Comment by boneskull** [comment]
anyway.  if this plugin encounters a `require('lodash')`, should it throw an exception?
