### ISSUE TITLE
Add doc note for lodash-fp

### ISSUE THREAD

**Issue by jdalton** [megawac/babel-plugin-lodash#6]

**Comment by gothy** [comment]
Yep, please! :)
Couldn't get it to work with lodash-fp installed and 'lodash' in babelrc plugins :(
Doing `import _ from 'lodash-fp';`

Gave me `Module not found: Error: Cannot resolve module 'lodash/collection/map' in ...`

**Comment by megawac** [comment]
@gothy it should work, for example see https://github.com/megawac/babel-plugin-lodash/blob/master/test/fixtures/lodash-fp-mix/actual.js (and other test fixtures)

**Comment by megawac** [comment]
Oh, that error means you didn't have lodash and lodash-fp installed.

`npm install lodash lodash-fp`

**Comment by jdalton** [comment]
Why is `lodash` needed? Docs!

**Comment by gothy** [comment]
Thanks! @megawac
